#!/usr/bin/env bash
# This bash function points to the IP Address of the domain

func ()
{
    res=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -1)
    echo "$2 $res" | awk '{print " The subdomain " $1 " is a " $5 " record and points to " $6 }'
}

# Checking the arguments passed

if [ "$#" -eq 1 ]
then
    func "$1" "www"
    func "$1" "lb-01"
    func "$1" "web-01"
    func "$1" "web-02"
elif [ "$#" -eq 2 ]
then
    func "$1" "$2"
fi

