#!/usr/bin/env bash

# Bash Script that accepts parameter
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
  
file_path=$1
ip_address=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip_address:~"
  
  
