#!/usr/bin/env bash
#   Insralling Nginx
#   Listening at port 80
#   Querying nginx

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configuring nginx
sudo ufw allow 'Nginx HTTP'

# Creating sample page
sudo echo "Hello World!" > /var/www/html/index.html

# Start Nginx
service nginx start
