#!/usr/bin/env bash
# Install and configure HAProxy on yyour lb-01 server

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure the server to both frontend and backend
echo "
frontend emycodes_frontend
    bind *:80
    mode http
    default_backend emycode_backend

backend emycode_backend
    balance roundrobin
    server 138989-web-01 54.174.11.183:80 check
    server 138989-web-02 54.90.61.187:80 check
">> /etc/haproxy/haproxy.cfg

# Enabling HAproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
