#!/usr/bin/env bash

# Installing ufw
sudo apt-get update -y
sudo apt-get install ufw -y

# Configuring ufw so that it blocks all incoming traffics
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enabling ufw
sudo ufw enable
