#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user

# Install nginx if it's not already installed
if ! which nginx > /dev/null; then
    apt-get update
    apt-get -y install nginx
fi

# Backing up  default configuration
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Updating configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

