#!/usr/bin/env bash
# Run Nginx as Nginx

# Checking if user doesn't exist,
if ! id -u nginx > /dev/null 2>&1; then
	echo "Creating user 'nginx'..."
	sudo adduser --system --no-create-home --disabled-login --disabled-password --group nginx
fi

# Stop nginx if it's currently running
sudo service nginx stop

# Backup default configuration
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Change ownership of nginx directories to nginx user
chmod 644 /etc/nginx/nginx.conf

# Change nginx user in nginx.conf
# Update configuration
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default


# Configure nginx to listen on all active IPs on port 8080
# sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# apache may interfere with nginx so kill the process if it is running
pkill apache2

# Start nginx
sudo -n service nginx restart
